repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: .*jinja$
      - id: check-json
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args: [--autofix, --indent=4, --no-ensure-ascii]

  - repo: https://github.com/verbicloud/prepare_commit_msg
    rev: v0.0.4
    hooks:
    - id: prepare-commit-msg-hook
