repos:
  - repo: local
    hooks:
    -   id: prepare-commit-msg
        name: Add commit instructions
        entry: python3 src/prepare_commit_msg/hook.py
        language: python
        stages: [prepare-commit-msg]
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: .*jinja$
      - id: check-json
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args: [--autofix, --indent=4, --no-ensure-ascii]
